name: run-cats-img

on:
  repository_dispatch:
   types: [trigger-workflow-2]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cats
        IMAGE_TAG: v0.1
      run: |
        cd cats/
        ls -ltra
        docker run -d -p 80:80 --name nodeapp $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost -vvv
       
    - name: Trigger next workflow
    if: success()
    uses: peter-evans/repository-dispatch@v1
    with:
     token: ${{ secrets.REPO_GHA_PAT }}
     repository: ${{ github.repository }}
     event-type: trigger-workflow-3
     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
